import { defineConfig } from 'tsup'

export default defineConfig([
  {
    entry: {
      index: 'src/index.ts',
      'svg/index': 'src/svg/index.ts',
      'shapeBoolean/index': 'src/shapeBoolean/index.ts',
      'predicates/index': 'src/predicates/index.ts',
      'segmentSet/index': 'src/segmentSet/index.ts',
      'hatch/index': 'src/hatch/index.ts',
      'circlePacking/index': 'src/circlePacking/index.ts',
      'morphology/index': 'src/morphology/index.ts',
      'transformation/index': 'src/transformation/index.ts',
      'processing/index': 'src/processing/index.ts',
      'conversion/index': 'src/conversion/index.ts',
      'contour/index': 'src/contour/index.ts',
      'hull/index': 'src/hull/index.ts',
      'triangulation/index': 'src/triangulation/index.ts',
      'pointSet/index': 'src/pointSet/index.ts',
      'optimisation/index': 'src/optimisation/index.ts',
      'voronoi/index': 'src/voronoi/index.ts',
      'construction/index': 'src/construction/index.ts',
      'tiling/index': 'src/tiling/index.ts',
      'polygonisation/index': 'src/polygonisation/index.ts',
      'meshing/index': 'src/meshing/index.ts',
    },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: true,
    splitting: false,
    treeshake: true,
    target: 'es2022',
  },
  {
    entry: {
      cli: 'src/cli.ts',
    },
    format: ['esm'],
    dts: false,
    sourcemap: true,
    clean: false,
    splitting: false,
    treeshake: true,
    target: 'es2022',
    banner: {
      js: '#!/usr/bin/env node',
    },
  },
])
